export const LEAD_STATUSES = {
  NEW: "NEW",
  CONTACTED: "CONTACTED",
  REQUEST_DOCUMENT: "REQUEST_DOCUMENT",
  DOCUMENT_RECEIVED: "DOCUMENT_RECEIVED",
  REQUEST_PENDING_DOCUMENTS: "REQUEST_PENDING_DOCUMENTS",
  ALL_DOCUMENTS_RECEIVED: "ALL_DOCUMENTS_RECEIVED",
  UNDER_BANK_PROCESS: "UNDER_BANK_PROCESS",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  DOCS_PENDING: "DOCS_PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  DISBURSED: "DISBURSED",
  CLOSED: "CLOSED",
};

export const STATUS_LABELS = {
  NEW: "New",
  CONTACTED: "Contacted",
  REQUEST_DOCUMENT: "Request Document",
  DOCUMENT_RECEIVED: "Document Received",
  REQUEST_PENDING_DOCUMENTS: "Request Pending Documents",
  ALL_DOCUMENTS_RECEIVED: "All Documents Received",
  UNDER_BANK_PROCESS: "Under Bank Process",
  ASSIGNED: "New",
  ACCEPTED: "Accepted",
  UNDER_REVIEW: "Under Review",
  DOCS_PENDING: "Docs Pending",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  DISBURSED: "Disbursed",
  CLOSED: "Closed",
};

export const LEGACY_STATUS_TO_STANDARD = {
  New: LEAD_STATUSES.NEW,
  Contacted: LEAD_STATUSES.CONTACTED,
  "Request Document": LEAD_STATUSES.REQUEST_DOCUMENT,
  "Document Received": LEAD_STATUSES.DOCUMENT_RECEIVED,
  "Request Pending Documents": LEAD_STATUSES.REQUEST_PENDING_DOCUMENTS,
  "Pending Documents": LEAD_STATUSES.REQUEST_PENDING_DOCUMENTS,
  "All Documents Received": LEAD_STATUSES.ALL_DOCUMENTS_RECEIVED,
  "Under Bank Process": LEAD_STATUSES.UNDER_BANK_PROCESS,
  Assigned: LEAD_STATUSES.ASSIGNED,
  Accepted: LEAD_STATUSES.ACCEPTED,
  "Under Review": LEAD_STATUSES.UNDER_REVIEW,
  "Bank Processing": LEAD_STATUSES.UNDER_BANK_PROCESS,
  "Bank Process": LEAD_STATUSES.UNDER_BANK_PROCESS,
  "Docs Pending": LEAD_STATUSES.REQUEST_PENDING_DOCUMENTS,
  "Pending Docs": LEAD_STATUSES.REQUEST_PENDING_DOCUMENTS,
  Approved: LEAD_STATUSES.APPROVED,
  Rejected: LEAD_STATUSES.REJECTED,
  Disbursed: LEAD_STATUSES.DISBURSED,
  Closed: LEAD_STATUSES.CLOSED,
};

export const ADMIN_STATUS_OPTIONS = [
  LEAD_STATUSES.NEW,
  LEAD_STATUSES.CONTACTED,
  LEAD_STATUSES.REQUEST_DOCUMENT,
  LEAD_STATUSES.DOCUMENT_RECEIVED,
  LEAD_STATUSES.REQUEST_PENDING_DOCUMENTS,
  LEAD_STATUSES.ALL_DOCUMENTS_RECEIVED,
  LEAD_STATUSES.UNDER_BANK_PROCESS,
  LEAD_STATUSES.ASSIGNED,
  LEAD_STATUSES.ACCEPTED,
  LEAD_STATUSES.UNDER_REVIEW,
  LEAD_STATUSES.DOCS_PENDING,
  LEAD_STATUSES.APPROVED,
  LEAD_STATUSES.REJECTED,
  LEAD_STATUSES.DISBURSED,
  LEAD_STATUSES.CLOSED,
];

export const BANK_STATUS_OPTIONS = [
  LEAD_STATUSES.NEW,
  LEAD_STATUSES.CONTACTED,
  LEAD_STATUSES.REQUEST_DOCUMENT,
  LEAD_STATUSES.DOCUMENT_RECEIVED,
  LEAD_STATUSES.REQUEST_PENDING_DOCUMENTS,
  LEAD_STATUSES.ALL_DOCUMENTS_RECEIVED,
  LEAD_STATUSES.UNDER_BANK_PROCESS,
  LEAD_STATUSES.DISBURSED,
];

export function normalizeStatus(status) {
  return STATUS_LABELS[status] ? status : LEGACY_STATUS_TO_STANDARD[status] || status || LEAD_STATUSES.NEW;
}

export function statusLabel(status) {
  return STATUS_LABELS[normalizeStatus(status)] || status || "New";
}
