export const LEAD_STATUSES = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  DOCS_PENDING: "DOCS_PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  DISBURSED: "DISBURSED",
  CLOSED: "CLOSED",
};

export const STATUS_LABELS = {
  NEW: "New",
  ASSIGNED: "Assigned",
  ACCEPTED: "Accepted",
  UNDER_REVIEW: "Under Review",
  DOCS_PENDING: "Docs Pending",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  DISBURSED: "Disbursed",
  CLOSED: "Closed",
};

export const LEGACY_STATUS_TO_STANDARD = {
  New: LEAD_STATUSES.NEW,
  Assigned: LEAD_STATUSES.ASSIGNED,
  Accepted: LEAD_STATUSES.ACCEPTED,
  "Under Review": LEAD_STATUSES.UNDER_REVIEW,
  "Bank Processing": LEAD_STATUSES.UNDER_REVIEW,
  "Docs Pending": LEAD_STATUSES.DOCS_PENDING,
  Approved: LEAD_STATUSES.APPROVED,
  Rejected: LEAD_STATUSES.REJECTED,
  Disbursed: LEAD_STATUSES.DISBURSED,
  Closed: LEAD_STATUSES.CLOSED,
};

export const ADMIN_STATUS_OPTIONS = [
  LEAD_STATUSES.NEW,
  LEAD_STATUSES.ASSIGNED,
  LEAD_STATUSES.ACCEPTED,
  LEAD_STATUSES.UNDER_REVIEW,
  LEAD_STATUSES.DOCS_PENDING,
  LEAD_STATUSES.APPROVED,
  LEAD_STATUSES.REJECTED,
  LEAD_STATUSES.DISBURSED,
  LEAD_STATUSES.CLOSED,
];

export const BANK_STATUS_OPTIONS = [
  LEAD_STATUSES.ASSIGNED,
  LEAD_STATUSES.ACCEPTED,
  LEAD_STATUSES.UNDER_REVIEW,
  LEAD_STATUSES.DOCS_PENDING,
  LEAD_STATUSES.APPROVED,
  LEAD_STATUSES.REJECTED,
  LEAD_STATUSES.DISBURSED,
];

export function normalizeStatus(status) {
  return STATUS_LABELS[status] ? status : LEGACY_STATUS_TO_STANDARD[status] || status || LEAD_STATUSES.NEW;
}

export function statusLabel(status) {
  return STATUS_LABELS[normalizeStatus(status)] || status || "New";
}
